"""added added_by field~

Revision ID: 409861bf6d65
Revises: 
Create Date: 2024-01-10 11:23:17.433407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409861bf6d65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinion', sa.Column('added_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opinion', 'added_by')
    # ### end Alembic commands ###
